// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFile(arg1, arg2) {
  return window['go']['main']['App']['CreateFile'](arg1, arg2);
}

export function GetChatResponse(arg1, arg2) {
  return window['go']['main']['App']['GetChatResponse'](arg1, arg2);
}

export function GetCoachInsight(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetCoachInsight'](arg1, arg2, arg3);
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadFolder(arg1) {
  return window['go']['main']['App']['ReadFolder'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}
