// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateFile(arg1:string,arg2:string):Promise<string>;

export function GetChatResponse(arg1:string,arg2:string):Promise<string>;

export function GetSuggestion(arg1:string,arg2:string,arg3:number):Promise<string>;

export function OpenFolder():Promise<main.FileNode>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadFolder(arg1:string):Promise<main.FileNode>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function UpdateFileIndex(arg1:string,arg2:string):Promise<void>;
